### ISSUE TITLE
Chrome extension no longer available

### ISSUE THREAD

**Issue by haleeben** [barbushin/php-console#100]
Hi

I noticed that the chrome extention is not longer available.

I already have it installed but in the chrome extentions section to now says that  "This extension violates the Chrome Web Store policy."

Whats going on?

**Comment by barbushin** [comment]
Hey,

There was some misunderstanding with Chrome Web Store policy auditors. They going to restore extension in a few days.

Sorry about that.

**Comment by haleeben** [comment]
That's good news. 

Thanks

**Comment by barbushin** [comment]
For now you can use this version https://chrome.google.com/webstore/detail/pjlgfjdeemcagkbhcdnffmjcagnbnhme

**Comment by barbushin** [comment]
Good news!

It's unlocked https://chrome.google.com/webstore/detail/php-console/nfhmhhlpfleoednkpnnnkolmclajemef

**Comment by haleeben** [comment]
Great thanks :)
