### ISSUE TITLE
very strange breakdown problem

### ISSUE THREAD

**Issue by assarte** [barbushin/php-console#101]
Hi,

it looks like the Chrome extension is unavailable and my previously installed PHP Console not working anymore.
![screenshot from 2015-11-22 19 34 12](https://cloud.githubusercontent.com/assets/5679362/11325526/61bfc33e-9150-11e5-8a0f-5169c42558ec.png)

**Comment by barbushin** [comment]
Hey,

There was some misunderstanding with Chrome Web Store policy auditors. They going to restore extension in a few days.

But for now you can use this version https://chrome.google.com/webstore/detail/pjlgfjdeemcagkbhcdnffmjcagnbnhme

Sorry about that.

**Comment by assarte** [comment]
Thank you! This tool saves a lot of time for me, I'm very happy about using of it!

**Comment by barbushin** [comment]
Good news!

It's unlocked https://chrome.google.com/webstore/detail/php-console/nfhmhhlpfleoednkpnnnkolmclajemef
