### ISSUE TITLE
Extension is not available in chrome store

### ISSUE THREAD

**Issue by ank212** [barbushin/php-console#102]
https://chrome.google.com/webstore/detail/php-console/nfhmhhlpfleoednkpnnnkolmclajemef

http://pastexen.com/i/IOl33akcxD.jpg

Extension is not available :(

**Comment by beardedlinuxgeek** [comment]
And if you have it installed, it is automatically disabled with the notice:

"This extension violates the Chrome Web Store policy."

**Comment by barbushin** [comment]
See #101

**Comment by ank212** [comment]
Nice! Thanks! Great tool!

**Comment by barbushin** [comment]
Good news!

It's unlocked https://chrome.google.com/webstore/detail/php-console/nfhmhhlpfleoednkpnnnkolmclajemef
