### ISSUE TITLE
Chrome shows alert that "This extension violates the Chrome Web Store policy." and disables the extension.

### ISSUE THREAD

**Issue by d3solutions** [barbushin/php-console#103]
Chrome extension was working properly until recently...

Now Chrome complains that "This extension violates the Chrome Web Store policy." and it forcibly disables the extension.  I can manually re-enable it, but at some point Chrome will inevitably disable it again.

Screenshot attached.

![extensions](https://cloud.githubusercontent.com/assets/786927/11381929/e42530d4-92b3-11e5-8250-d9876817da84.png)

**Comment by d3solutions** [comment]
Also, you seem to have been removed from the Chrome web store:
https://chrome.google.com/webstore/detail/php-console/nfhmhhlpfleoednkpnnnkolmclajemef

**Comment by barbushin** [comment]
Hey,

There was some misunderstanding with Chrome Web Store policy auditors. They going to restore extension in a few days.

But for now you can use this version https://chrome.google.com/webstore/detail/pjlgfjdeemcagkbhcdnffmjcagnbnhme

Sorry about that.

**Comment by d3solutions** [comment]
Works, thanks!

It wouldn't have been such a big problem if this weren't such an awesome tool!
Thanks so much!!

**Comment by barbushin** [comment]
Good news! 

It's unlocked https://chrome.google.com/webstore/detail/php-console/nfhmhhlpfleoednkpnnnkolmclajemef
