### ISSUE TITLE
не выводит debug-информация во время ajax-запроса, идет утечка памяти

### ISSUE THREAD

**Issue by olegius88** [barbushin/php-console#104]
повторятся ошибки:
1)
в extensions::uncaught_exception_handler:8
Error in response to tabs.get: TypeError: Cannot read property 'status' of undefined
    at Object.callback (chrome-extension://pjlgfjdeemcagkbhcdnffmjcagnbnhme/js/messages.js:68:11)
    at chrome-extension://pjlgfjdeemcagkbhcdnffmjcagnbnhme/js/messages.js:67:16

![image](https://cloud.githubusercontent.com/assets/7477933/11446704/ea46ede6-9564-11e5-8ed5-747db227176b.png)

2)
Unchecked runtime.lastError while running tabs.get: No tab with id: 2056.
![image](https://cloud.githubusercontent.com/assets/7477933/11446726/48fee2b2-9565-11e5-8f3e-b811d484d9c0.png)

в диспетчере задач браузера страшная утечка в течении 10 минут
![image](https://cloud.githubusercontent.com/assets/7477933/11446716/23d01cea-9565-11e5-833b-704ac5141417.png)

**Comment by olegius88** [comment]
данные ошибки появляются как при прямом ajax-запросе, так и при кросс-сайтовом, с расширения хрома

**Comment by barbushin** [comment]
Используйте оригинальную версию https://chrome.google.com/webstore/detail/php-console/nfhmhhlpfleoednkpnnnkolmclajemef

**Comment by olegius88** [comment]
![image](https://cloud.githubusercontent.com/assets/7477933/11451435/394d8c2a-95f0-11e5-940a-7faea2dd152d.png)
поставил оригинальную версию, ошибки продолжаются появляться
