### ISSUE TITLE
Uncaught SyntaxError: Unexpected token П

### ISSUE THREAD

**Issue by olegius88** [barbushin/php-console#105]
Циклически повторяется 5 раз подряд 
![image](https://cloud.githubusercontent.com/assets/7477933/11453828/980301ec-9644-11e5-9962-f0dbfe06e17c.png)
когда это случается, расширение не передает данные в консоль.

**Comment by barbushin** [comment]
А можете выслать дамп запроса?

**Comment by olegius88** [comment]
запрос методом POST передает цифру. Я проанализировал ситуацию. как я понял, на уровне кода проблема в том, что количество в байтах передаваемой информации превышает header limit  сервера. я в Helper.php в методе debug добавил подсчет передаваемой информации, и если лимит превышает 4000 байт, останавливаю метод. Проблема решилась вроде как.

**Comment by barbushin** [comment]
Рад, что ваша проблема решилась. А подскажите, какой у вас веб-сервер? Я старался прописать ограничения на размер заголовков подходящими для большинства веб-серверов. Странно, что в вашем случае это реальные ограничения оказались ещё меньше.
