### ISSUE TITLE
icon not showing depending on server

### ISSUE THREAD

**Issue by Polfo** [barbushin/php-console#106]
PHP console works wonderfully with both the live demo page and my primary web server. Thank you for this.
However, the PHP console icon is not showing in the chrome address bar when I use PHP console on an other server (OVH hosting), altough that server's HTTP Response Header contains
`PHP-Console-Postpone:{"protocol":5,"isPostponed":true,"id":"108284820715439790772530902"}`
Both servers installed PHP-Console through ´https://github.com/nekojira/wp-php-console´
This issue is probably due to some server setting, but how do I debug this?

Using:
Client `PHP Console` version 3.0.38
Server `WP PHP Console` version 1.3.9 including `PHP Console` version 3.1

**Comment by barbushin** [comment]
I guess there is different headers limit in your OVH web server. You can check it with script included in php-console package, in /examples dir. See http://php-console.com/instance/examples/#detect_headers_limit

**Comment by barbushin** [comment]
You can check it very quickly, just set some minimal headers limit as `PhpConsole\Connector::getInstance()->setHeadersLimit(1024);`

**Comment by Polfo** [comment]
I ran `detect_headers_limit`. It reports OVH server's limit is `1275000`, so it is an other issue.
I now also ran PhpConsole stand alone (not within the WordPress environment) and it works fine.
So I will investigate there. Thank you very much.
