### ISSUE TITLE
Smarty

### ISSUE THREAD

**Issue by alfiqmiq** [barbushin/php-console#112]
Have a question:

Did You plan to add specific smarty template debugging info ?

[http://www.smarty.net/docsv2/en/chapter.debugging.console.tpl](http://www.smarty.net/docsv2/en/chapter.debugging.console.tpl)

**Comment by barbushin** [comment]
Unfortunately, right now I don't have a time for this. There are so many template engines, and I can't create debugging info for every one. To be honest, right not I'm working on PHP Console v4.0. There will be a lot of new interesting features, and integration with Symfony/Zend/Laravel frameworks, so template data will be automatically handled by PHP Console.
