### ISSUE TITLE
some improvements

### ISSUE THREAD

**Issue by alfiqmiq** [barbushin/php-console#113]
I'm wondering is it possible to have some console command like `console.log` or `console.trace` something about: console.php that can be run directly from chrome console not from "remote console window" as is think it would be easier to use.

What do U think about?

**Comment by alfiqmiq** [comment]
any progress or comment?

**Comment by barbushin** [comment]
Not sure that I understand that idea.

**Comment by alfiqmiq** [comment]
now we have to open console window (chrome extension) to get information from phpconsole, but im wondering if it will be possible to run command directly on chrome console (chrome developer toools)
