### ISSUE TITLE
Трассировка detectTraceAndSource в виде javascript обекта

### ISSUE THREAD

**Issue by olegius88** [barbushin/php-console#114]
мне кажется было бы намного удобнее, если бы трассировка была не в виде списка строк:
![image](https://cloud.githubusercontent.com/assets/7477933/13197980/1cb8f3e6-d827-11e5-8778-ab2f8cc172bc.png)
а как javascript объект:
![image](https://cloud.githubusercontent.com/assets/7477933/13197987/33f031c8-d827-11e5-8a60-37a906fc82f0.png)
![image](https://cloud.githubusercontent.com/assets/7477933/13197991/3dff1d50-d827-11e5-8e7d-65d45b728cdf.png)
то есть строки трассировки. 
Или в виде опции, было бы очень удобно. спасибо

**Comment by alfiqmiq** [comment]
engish, isnt it a preffered language on this site ?

**Comment by barbushin** [comment]
@olegius88 speak English plz
