### ISSUE TITLE
Codeigniter 2.x

### ISSUE THREAD

**Issue by jeffjones72** [barbushin/php-console#115]
Is there documentation on integrating with CI 2.x?

I see bundles for other MVC platforms, but not for CI.

Thank you

**Comment by barbushin** [comment]
Most of bundles was developed by another programmers, not by me. So there is no bundle for CI because it's not so popular. You can be the first, who will do this.

**Comment by jeffjones72** [comment]
I saw a closed issue for a CI 3 user.

Bummer

**Comment by barbushin** [comment]
Some guy just integrated php console with CI by himself. And can do it also, there is nothing hard to do.
