### ISSUE TITLE
Chrome Hanging with this module

### ISSUE THREAD

**Issue by teuma86** [barbushin/php-console#119]
Hi

I have noticed my chrome hanging, as a few work friends.  After Trial and error, we have worked out its this extension.

This is both 48 and 49 Chrome version
OS:  Various MAC OSX machines (latest)

Example:
going to a large JS used website such as BBC, getsurrey.co.uk. Chrome browser hangs and page is slow to load. Approx time 20 seconds to 3 minutes.

Testing:
Through trial and error of disabling extension.  With this extension disabled, the hanging problem goes away.

Please fix as I love this extension

**Comment by teuma86** [comment]
Sorry, this is for JavaScript Errors Notifier, please let me know if this is not the right place to report issue, I cant find an alternative

**Comment by barbushin** [comment]
@teuma86 Could you please send me URL of page where I can reproduce this bug?
