### ISSUE TITLE
WordPress Plugin only works in backend

### ISSUE THREAD

**Issue by nmggithub** [barbushin/php-console#122]
The Wordpress Plugin works, but I can only successfully see the results if I am at a url under "wp-admin". Otherwise I get:
`Console was cleared                                                                                                                 content.js:4`

In the console.

**Comment by nmggithub** [comment]
This is STILL not working

**Comment by nmggithub** [comment]
STILL not working. Please help.

**Comment by barbushin** [comment]
I'm not author of WordPress Plugin. See https://github.com/unfulvio/wp-php-console
