### ISSUE TITLE
502 Server error

### ISSUE THREAD

**Issue by Doctorrr** [barbushin/php-console#126]
After several hours of a normal work and some rest,
i came back to 502 Server error + errors in Chrome console::

> blob:https%3A//mydomain.com/29d5804c-f27f-45aa-8e77-53a90a9096a4 Failed to load resource: the server responded with a status of 404 (Not Found)
> blob:https%3A//mydomain.com/29d5804c-f27f-45aa-8e77-53a90a9096a4 Failed to load resource: the server responded with a status of 404 (Not Found)

My configuration:
```
require_once( $_SERVER['DOCUMENT_ROOT'].'/php-console/src/PhpConsole/__autoload.php' );
$connector = PhpConsole\Helper::register();

if($connector->isActiveClient()) {
    $handler = PC::getHandler();
    $handler->start();

    $connector->setSourcesBasePath($_SERVER['DOCUMENT_ROOT']);
    $connector->setPassword( '12345' );
    $connector->enableSslOnlyMode();

    $evalProvider = $connector->getEvalDispatcher()->getEvalProvider();
    $evalProvider->addSharedVar('uri', $_SERVER['REQUEST_URI']);
    $evalProvider->addSharedVarReference('post', $_POST);
    $connector->startEvalRequestsListener();

}
```
Updated Chrome on Win 10.

**Comment by barbushin** [comment]
Can't reproduce it. Try to clear cookies and reinstall extension.

**Comment by wangyouw** [comment]
maybe the header too big ,you can see the nginx error log  (upstream sent too big header while reading response header from upstream)
