### ISSUE TITLE
disable popup

### ISSUE THREAD

**Issue by CaptainN** [barbushin/php-console#127]
How can I disable the popup? It shows an alert for any error - even on non-php sites. I really don't need that, since I already have the error in the error console (I especially don't need it on sites I'm not developing without PHP). Thanks!

**Comment by CaptainN** [comment]
If there isn't a way now, I suggest following how they did it in the Redux devtools extension, which simply provides a checkbox to turn off the popup inside "options".

**Comment by barbushin** [comment]
![image](https://cloud.githubusercontent.com/assets/683352/18463657/654e9c14-7994-11e6-8d8f-1caf28085d91.png)
