### ISSUE TITLE
No messages in DevTools console

### ISSUE THREAD

**Issue by cronfy** [barbushin/php-console#130]
Problem started today. In Chrome Developer Tools console I do not see most of messages from PhpConsole when doing AJAX requests. Messages appear as notifications in right bottom corner of the browser window, but not in the console. Messages from not-AJAX requests are shown ok.

Sometimes they go to console though.. I can't see any pattern.

```PHP-console``` and ```PHP-Console-Postpone``` headers present in the response.

I tried restarting browser and reinstalling the extension - does not help.

How do I investigate this problem?

**Comment by barbushin** [comment]
I can't reproduce it. Could you share some URL where I can test it?

**Comment by cronfy** [comment]
I happens in a huge project, I have no idea right now about how to simplify the test. I will think about sharing, but before I did it maybe it is posible to collect some debug data for you somehow?

**Comment by barbushin** [comment]
Please check if there are some JS errors in console https://github.com/barbushin/php-console/wiki/How-to-report-bug-or-feature#attach-google-chrome-extension-javascript-errors (see Attach Google Chrome extension JavaScript errors).

Also please check that AJAX request domain is same as page tab domain.

**Comment by cronfy** [comment]
Sorry, I do not think I will investigate it further, because I switched to XDebug + PHPStorm for PHP Debugging instead of php-console.
