### ISSUE TITLE
Recently running >100% cpu

### ISSUE THREAD

**Issue by wrabit** [barbushin/php-console#157]
The extension has been running frequently up over 100% (discovered by the Chrome task manager) and I have to restart the instance to return to normal. I am not doing anything heavy with the debugging. Any clue what to check?

**Comment by Chematronix** [comment]
I see a *ton* of errors in background.html causing this:

42032 Error handling response: TypeError: Cannot read property 'status' of undefined
    at <URL>
14411 Unchecked runtime.lastError: No tab with id: 5105.
12011 Unchecked runtime.lastError: No tab with id: 4285.
15209 Unchecked runtime.lastError: No tab with id: 5153.
400 Unchecked runtime.lastError: No tab with id: 6246.
85531234 log entries are not shown.

**Comment by barbushin** [comment]
Fixed in release 3.0.39
