### ISSUE TITLE
PC::debug() not working locally with latest Chrome

### ISSUE THREAD

**Issue by Vyeadiai** [barbushin/php-console#161]
I have a debug statement like so in my WP shortcode function:

PC::debug('TEST');

The shortcode function executes fine but the debug statement shown above does not show in the console. It was working fine a few days ago, I was able to print debug statements in the console. I believe a new Chrome release has broken this. I have my Chrome browser set to auto update, and that is the only thing that has changed, I have not updated WP, nothing. There is no warnings or errors, but the debug statement no longer appears as it was a few days ago.

This is my Chrome version (just released a few days ago):
Version 77.0.3865.90 (Official Build) (64-bit)

Wordpress version: 5.2.3
PHP version: 7.2.9

OS: macOS Mojave 10.14.4 (18E226)

Please test and see it is not working. Thanks

**Comment by Vyeadiai** [comment]
Not sure why but it starter working again randomly,

**Comment by lbngoc** [comment]
Hello @Vyeadiai , I known this issue was closed, but it seems the extension is not working again with the latest Chrome ( 84.0.4115.5 )
Could you please do a test in your end?
