### ISSUE TITLE
php7.4RC3 with enable opcache fpm crash

### ISSUE THREAD

**Issue by haohetao** [barbushin/php-console#162]
docker image:php:7.4-rc-fpm
https://hub.docker.com/_/php?tab=tags&page=1&name=7.4-rc-fpm
yii 2.0.28
php console latest
php7.4 with opencache enable trigger php-fpm crash(child 23 exited with code 11)
the logs

> php74_1        | [14-Oct-2019 16:29:58.439656] DEBUG: pid 1, fpm_event_loop(), line 430: event module triggered 2 events
php74_1        | [14-Oct-2019 16:29:58.439695] DEBUG: pid 1, fpm_got_signal(), line 82: received SIGCHLD
php74_1        | [14-Oct-2019 16:29:58.439702] DEBUG: pid 1, fpm_event_loop(), line 430: event module triggered 1 events
php74_1        | [14-Oct-2019 16:29:58.439722] WARNING: pid 1, fpm_children_bury(), line 259: [pool www] child 23 exited with code 11 after 398.929859 seconds from start
php74_1        | [14-Oct-2019 16:29:58.440162] NOTICE: pid 1, fpm_children_make(), line 428: [pool www] child 25 started

**Comment by barbushin** [comment]
I think it's because PHP 7.4 is just in release candidate. Let's test it with release.

**Comment by haohetao** [comment]
php7.4 final release always exists this problem
