### ISSUE TITLE
Do not convert array to object

### ISSUE THREAD

**Issue by Polfo** [barbushin/php-console#76]
Thanks for all your investment in this barbushin

	$xx = [1,2];
	PC::debug($xx, 'numeric');
	$xx = [1=>1,'b'=>'b'];
	PC::debug($xx, 'associative');

is displayed as:
![image](https://cloud.githubusercontent.com/assets/10303392/5798644/c01236c0-9fc9-11e4-94c7-71d5a7786353.png)

`Object {1: "1", b: "b"}` is confusing to me, I would expect something consistent with the first display like `[1: "1", "b": "b"]` 

Maybe it is not possible due to a conversion to javascript, but then it would be nice if it was documented.

**Comment by barbushin** [comment]
There is no way to fix it. It's default behavior of JavaScript `console.log()` method.
