### ISSUE TITLE
jump to file (phpDesigner8)

### ISSUE THREAD

**Issue by lipefl** [barbushin/php-console#77]
Im using phpDesigner8 and i cant figure it out the command line to the "jump to file" feature. I tried all options, i dont know if its possible.
I tried with gVim and it worked fine.

**Comment by barbushin** [comment]
Every IDE has it's own argument names to open some file:line. Some IDE do not have this arguments. You should try to check IDE documentation or try something like `--help` or `/?` to get list of command line arguments.

I do not use PhpDesigner so I don't know how to help you.
