### ISSUE TITLE
OSX - Apache - Pow: address bar button not showing

### ISSUE THREAD

**Issue by g13013** [barbushin/php-console#78]
I had difficulties to show to toolbar button, I tried everything but no solution, until I try to load a server using "php -S" , and it WORK, so it might be a problem related to Apache or Pow.

Any idea ?

**Comment by barbushin** [comment]
I this the problem is in Pow. Try to decrease headers limit size in PhpConsole config.

**Comment by g13013** [comment]
I confirm it is due to Pow, but reducing headers limit size didn't work :(

**Comment by barbushin** [comment]
I don't have any ideas about Pow :( Check if there is `PHP-Console` in response headers, and check that there is a cookie `php-console-server` and `php-console-client`.

**Comment by g13013** [comment]
Yes there is response headers and cookies, but what i've noticed is that they are all in lowercased when served with pow, could it be the problem ?

headers sent
php-console-postpone
php-console

cookies:
php-console-client
php-console-server

**Comment by g13013** [comment]
Thanks for your help, it's its related with Pow I close this issue
