### ISSUE TITLE
sess_ files

### ISSUE THREAD

**Issue by landwire** [barbushin/php-console#79]
Hi there,
as far as I can see PHP Console creates sess_ files.

Can I somehow change the location of those files or just stop PHP COnsole generating them?
Thanks,
Sascha

**Comment by barbushin** [comment]
Hey

By default php-console use $_SESSION to store postponed response data. But you can set another type of storage. See `PhpConsole\Connector::setPostponeStorage()` and https://github.com/barbushin/php-console/tree/master/src/PhpConsole/Storage.

Cheers.
