### ISSUE TITLE
Cakephp integration

### ISSUE THREAD

**Issue by serchmail** [barbushin/php-console#80]
Has anybody install php-console with cakephp?

I have copy php-console in Vendor directory and add the include:
App::import('Vendor', 'php-console-master', array('file' => 'php-console-master\src\PhpConsole\__autoload.php'));

I have try copy folder in webroot (with different include).

Some functions are right but I can't execute php code with "console eval".

Any suggestions?

Thanks in advance.

**Comment by barbushin** [comment]
Can you attach source code how you enabled `console eval`?

**Comment by serchmail** [comment]
Of course.
As aditional information, when I push Ctrl-Enter, console sais:
"content.js:4 Console was cleared".

I have put this code in App/Config/bootstrap.php:

// require_once('../webroot/php-console-master/src/PhpConsole/__autoload.php'); //Another try.
App::import('Vendor', 'php-console-master', array('file' => 'php-console-master\src\PhpConsole\__autoload.php'));

$password = "**PaSs**"; //Change to real pass
if(!$password) {
    die('Please set $password variable value in ' . __FILE__);
}

$connector = PhpConsole\Connector::getInstance();
$connector->setPassword($password); // Eval requests listener can be started only in password protected mode

$evalProvider = $connector->getEvalDispatcher()->getEvalProvider();
$evalProvider->disableFileAccessByOpenBaseDir(); // means disable functions like include(), require(), file_get_contents() & etc
$evalProvider->addSharedVar('uri', $_SERVER['REQUEST_URI']); // so you can access $_SERVER['REQUEST_URI'] just as $uri in terminal
$evalProvider->addSharedVarReference('post', $_POST);
$connector->startEvalRequestsListener(); // must be called after all configurations

**Comment by barbushin** [comment]
Try to remove this line `$evalProvider->disableFileAccessByOpenBaseDir();`. And I recommend to use `require_once('../webroot/php-console-master/src/PhpConsole/__autoload.php');` for autoload to be called before any framework calls.

**Comment by serchmail** [comment]
I have make the suggested changes and it's working fine.
Thanks for your fast and precise information.
