### ISSUE TITLE
undefined variable in background.js

### ISSUE THREAD

**Issue by TheEmberLeader** [barbushin/php-console#84]
Hey barbushin, I'm using your plugin in tandem with nekojira's wp one if that's important.  When I reload a page on a develop site to get errors, I never see the password button to login, and I get an error when I inspect the extension in chrome.  It says: 

extensions::uncaught_exception_handler:8 Error in response to tabs.get: TypeError: Cannot read property 'isSslOnlyMode' of undefined
    at D.a.q (chrome-extension://nfhmhhlpfleoednkpnnnkolmclajemef/background.js:25:173)
    at Object.callback (chrome-extension://nfhmhhlpfleoednkpnnnkolmclajemef/background.js:17:320)
    at x (chrome-extension://nfhmhhlpfleoednkpnnnkolmclajemef/background.js:17:232)
    at chrome-extension://nfhmhhlpfleoednkpnnnkolmclajemef/background.js:17:407
    at XMLHttpRequest.l.onreadystatechange (chrome-extension://nfhmhhlpfleoednkpnnnkolmclajemef/background.js:19:105)

Anyway, I'm not sure if this is related to nekojira or yourself.  But any help would be appreciated.

**Comment by barbushin** [comment]
Hey! Can you provide link to that page? I'll try to fix it as soon as possible.

**Comment by TheEmberLeader** [comment]
Sure, it's johnjhoward.net. The password for the wp php console is 123456
if that's needed.

**Comment by barbushin** [comment]
Thanks. I removed your message, so password will not be shared with another GitHub users.

**Comment by TheEmberLeader** [comment]
Oh, thanks. I'm emailing you so I wasn't aware of that.

**Comment by barbushin** [comment]
I've fixed `Cannot read property 'isSslOnlyMode' of undefined` in version `3.0.27`. Try to reinstall extension. And as before, it works on your site, see http://i.imgur.com/XsufheU.png & http://i.imgur.com/72Cna5G.png

Also try if your version of PHP Console extension works on http://php-console.com/instance/examples/#eval_terminal

**Comment by TheEmberLeader** [comment]
OK, I'll get to it tomorrow. Thanks!

**Comment by TheEmberLeader** [comment]
Hmm. Now I reinstalled and am getting two additional errors:

Error in response to cookies.get: TypeError: x is not a function
    at Object.callback (chrome-extension://nfhmhhlpfleoednkpnnnkolmclajemef/background.js:7:479)
    at chrome-extension://nfhmhhlpfleoednkpnnnkolmclajemef/background.js:7:268
    at IDBRequest.index.get.onsuccess (chrome-extension://nfhmhhlpfleoednkpnnnkolmclajemef/background.js:36:239)handler @ extensions::uncaught_exception_handler:8
extensions::uncaught_exception_handler:8

 Error in response to cookies.get: Error: Attempting to use a disconnected port object
    at chrome-extension://nfhmhhlpfleoednkpnnnkolmclajemef/background.js:9:457
    at chrome-extension://nfhmhhlpfleoednkpnnnkolmclajemef/background.js:8:350
    at Object.callback (chrome-extension://nfhmhhlpfleoednkpnnnkolmclajemef/background.js:7:479)
    at chrome-extension://nfhmhhlpfleoednkpnnnkolmclajemef/background.js:7:268
    at IDBRequest.index.get.onsuccess (chrome-extension://nfhmhhlpfleoednkpnnnkolmclajemef/background.js:36:239)

**Comment by barbushin** [comment]
Are you using `3.0.31` version?

**Comment by TheEmberLeader** [comment]
Chrome only updated to 3.0.29, I'll try to update again.


   *Gabe Blodgett, *   Co-Owner & Director of Marketing and Engineering ,
MPzero Studios
  [image: photo]
 <http://facebook.com/MPzeroStudios>
<http://linkedin.com/comany/mpzero-studios>
<http://plus.google.com/+Mp0Studios>  <http://twitter.com/mpzerostudios>
<http://www.youtube.com/channel/UC7ksEPpuepoSyeVC3-jk2kQ>
Phone: 541-786-1675
 Email: gabe@mp0studios.com
 Website: MPzeroStudios.com
 Address: 1207 10th st, La Grande OR 97850
     Get a signature like this: Click here!
<http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjkzOTI3IiwgImUiOiAiNTczMjU2ODU0ODc2OTc5MiJ9>

**Comment by TheEmberLeader** [comment]
Okay, updated to 3.0.31, a new error shows up, but I don't see what it's
referring at all.  Here's the image:


   *Gabe Blodgett, *   Co-Owner & Director of Marketing and Engineering ,
MPzero Studios
  [image: photo]
 <http://facebook.com/MPzeroStudios>
<http://linkedin.com/comany/mpzero-studios>
<http://plus.google.com/+Mp0Studios>  <http://twitter.com/mpzerostudios>
<http://www.youtube.com/channel/UC7ksEPpuepoSyeVC3-jk2kQ>
Phone: 541-786-1675
 Email: gabe@mp0studios.com
 Website: MPzeroStudios.com
 Address: 1207 10th st, La Grande OR 97850
     Get a signature like this: Click here!
<http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjkzOTI3IiwgImUiOiAiNTczMjU2ODU0ODc2OTc5MiJ9>

**Comment by barbushin** [comment]
I dont see any image attached

**Comment by barbushin** [comment]
I opened http://johnjhoward.net, authorized in php console, and I see that it works. All JS errors in JS console are not relative to php console, it's because of internal site scripts. If I disable php console I see the same JS errors. And there are no errors in JS console of php console background page.

**Comment by barbushin** [comment]
See http://i.imgur.com/dfvbB69.png  `mlPageTracker` and `sendTrackEvent` are in `widget-narrow.js`, and it does not belong to php console.

**Comment by TheEmberLeader** [comment]
When I go to the extensions tab and click "collect errors" under the
plugin, it shows an error that says "Cannot load extension with file or
directory name _metadata. Filenames starting with "_" are reserved for use
by the system." in reference to the
"background": { "page": "background.html" },

section.


   *Gabe Blodgett, *   Co-Owner & Director of Marketing and Engineering ,
MPzero Studios
  [image: photo]
 <http://facebook.com/MPzeroStudios>
<http://linkedin.com/comany/mpzero-studios>
<http://plus.google.com/+Mp0Studios>  <http://twitter.com/mpzerostudios>
<http://www.youtube.com/channel/UC7ksEPpuepoSyeVC3-jk2kQ>
Phone: 541-786-1675
 Email: gabe@mp0studios.com
 Website: MPzeroStudios.com
 Address: 1207 10th st, La Grande OR 97850
     Get a signature like this: Click here!
<http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjkzOTI3IiwgImUiOiAiNTczMjU2ODU0ODc2OTc5MiJ9>

**Comment by barbushin** [comment]
I can't find any `Collect errors` tab or button on extensions page. Usually I check extension errors in `background.html` console, see http://i.imgur.com/GTtsv6z.png Could you please send me screen screenshot where can I find that `collect errors` link?

**Comment by TheEmberLeader** [comment]
Here's how you enable chrome to collect error: (click on the 1.)  To view errors, click on the 2. when you reload the webpage you want to use it on.
![captureerrors](https://cloud.githubusercontent.com/assets/13141940/8503019/549ab77a-216d-11e5-9286-c41e79a9ff23.PNG)

Here's the error I'm getting:
![error](https://cloud.githubusercontent.com/assets/13141940/8503028/69d736e0-216d-11e5-8369-654abbd967ed.PNG)

**Comment by barbushin** [comment]
Wow.. I'm using Chrome version `43.0.2357.130 m` and I don't have Collect errors option. Also there is no `_metadata` file or directory in extension files list. Whatever, php-console still not works on your PC?

**Comment by TheEmberLeader** [comment]
I'm using Chrome version 45.0.2438.3 dev-m (64-bit).  For me Chrome automatically updates, so I'm not sure what the issue is. 
No, it still doesn't work.

**Comment by barbushin** [comment]
So you're using `dev` version? Sorry, but php-console is based and tested only on stable Chrome version. And as I said before: there is no `_metadata` file or directory in extension files list, so you should check if there is something wrong with your Chrome or website. 

Let me know if you'll have a problem with any version of stable Chrome edition. Thank you.

**Comment by TheEmberLeader** [comment]
Okay, I uninstalled Chrome, downloaded the same version that you have and suddenly, it works!  Thanks for the help, and I'm sorry to bug you!  I was unaware that I was running the dev version (a bad idea really).  Anyway, I appreciate everything!
