### ISSUE TITLE
Slim Framework adapter

### ISSUE THREAD

**Issue by amenadiel** [barbushin/php-console#86]
Hi @barbushin 

I've made a [PHP Console adapter for Slim Framework](https://github.com/amenadiel/SlimPHPConsole). 

I was using [Slim](https://github.com/slimphp/Slim), then [Slim-Monolog](https://github.com/Flynsarmy/Slim-Monolog), then [Monolog](https://github.com/Seldaek/monolog) just to instantiate Monolog's PHPConsoleHandler to debug to PHPConsole. 

It was cumbersome so I decided to remove the middle men and log directly to PHPConsole.

```php
    $logwriter = new \Amenadiel\SlimPHPConsole\PHPConsoleWriter(true);
    $app = new \Slim\Slim(array(
        'log.enabled' => true,
        'log.level' => \Slim\Log::DEBUG,
        'log.writer' => $logwriter
    ));

    $app->log->debug('Debug called!');
```

it can be installed with composer:

```sh
composer require amenadiel/slim-phpconsole
```

I hope it might be useful to someone.

**Comment by barbushin** [comment]
Thanks, Felipe! I've added link to your adapter in README.md https://github.com/barbushin/php-console/blob/master/README.md#slim-framework

:+1:
