### ISSUE TITLE
source of chrome extension

### ISSUE THREAD

**Issue by amenadiel** [barbushin/php-console#87]
Hi @barbushin 

I wonder, where do you keep the source code for the chrome extension? If you don't want to publish it I understand, of course. However, I just wanted to see how hard would it be to make it use `console.info`, `console.warn` and `console.debug` instead of just `console.log`, depending on the backend tag. Maybe change colors as well.

**Comment by barbushin** [comment]
I'm working on next version of extention, so old source code is kind of deprecated. Before I though about using console.info, but it will looks not so nice as it is now. Also I don't think that there is a good idea to separate E_WARNING and E_ERROR like different level errors. As for me all of them are enough critical, even E_NOTICE sometime is critical, so I think they should be colored in the same way :)

**Comment by amenadiel** [comment]
Yeah, I didn't mean the error handler. Errors and exceptions should still be console.errors and display in red.

But I thought that maybe there would be a way to bind specific tags to console methods. For example accepting a fourth parameter for `\PhpConsole\Handler::debug` which defaults to 'log' but can also be 'info', 'debug','warn'.

Perhaps even console.table and console.time / timeEnd could be used this way.

**Comment by barbushin** [comment]
Yeah, that's gonna be in the next version. console.table also :)
