### ISSUE TITLE
Problem with CodeIgniter redirect() method

### ISSUE THREAD

**Issue by digitaloutback** [barbushin/php-console#89]
I am using with Codeigniter 3 (successfully used with CI before). No $_POST data is being processed, when I exclude the php-console files, it is working again, any tips?

**Comment by barbushin** [comment]
There is nothing like `$_POST = ....` in php-console, it does not change $_POST data. You should try to debug in what moment $_POST becomes empty. In the request start? When `PhpConsole\Connector` is initialized?

**Comment by digitaloutback** [comment]
It loses is after `$connector = PhpConsole\Connector::getInstance();`

**Comment by barbushin** [comment]
So now you need to check in what exactly line $_POST becomes empty. Just add debug code like `empty($_POST) && var_dump(__LINE__);` in every line of `PhpConsole\Connector::initConnection()` method.

**Comment by digitaloutback** [comment]
Ok, it was to do with using CI's redirect(). When I use redirect() in a controller, it's not returning any of my data called with pc::debug($var), even though I am using it before the redirect() call, in the same request..

Empty phpconsole output for:
```
	function notifications() 
	{
		pc::debug($_POST,'post');
		if ($input = $this->input->post(null,true)) {
			redirect('user/notifications', 'refresh');
		}
	}
```

Phpconsole outputs for:
```
	function notifications() 
	{
		pc::debug($_POST,'post');
		if ($input = $this->input->post(null,true)) {
			//redirect('user/notifications', 'refresh');
		}
	}
```

**Comment by barbushin** [comment]
I can try to debug it by myself, if there is a public web site. Otherwise you need to debug it by yourself... And try to check https://github.com/barbushin/php-console#troubleshooting-with-_session-handler-overridden-in-some-frameworks

**Comment by digitaloutback** [comment]
Ok, in development. I will take a look, redirect does a header redirect with `header('Location: $url', true, 302/303/307)`

**Comment by barbushin** [comment]
There is some algorithm in Chrome extension code, that detects redirects. If you want me to debug it, I'll need a link to that website. You can send it to barbushin@gmail.com

**Comment by barbushin** [comment]
I don't see the way to debug and fix this issue, so I'm closing it.
