### ISSUE TITLE
Possible to detach from toolbar?

### ISSUE THREAD

**Issue by examinedliving** [barbushin/php-console#93]
When I'm evaluating live, it's annoying to keep switching back and forth.  It'd be nice to have it detached, or - better yet - attached to dev. console.

**Comment by barbushin** [comment]
Hey! What do you mean `evaluating live`?

**Comment by examinedliving** [comment]
Using PHP Console as a repl.  Evaluating PHP code in the console.  I'm not sure what's unclear.

**Comment by barbushin** [comment]
It could be implemented as separate tab in Dev Tools. But it's a big part of work, and I'm not sure that I have a free time for this right now.

**Comment by examinedliving** [comment]
Gotcha.  That's what I was after.  Something to keep in mind for the future.  It's a good plugin.  Thanks for your work.
