### ISSUE TITLE
A potential bug or conflict need to be investigated.

### ISSUE THREAD

**Issue by ukalpa** [barbushin/php-console#95]
Hi there

I found php-console has a potential bug may cause php-script exit termination. I installed a Magento-1.9.2.1 on my environment and import php-console in the "{magento}/api.php"

```
if(!function_exists('dddd'))
{
    require_once 'C:\www\php-console\src\PhpConsole\__autoload.php';
    PhpConsole\Helper::register();
    PC::getConnector()->getDebugDispatcher()->detectTraceAndSource = true;
    function dddd($msg = '1234567890123', $title = '')
    {
            static $dddd_i = 0;
            ($title === '') ?: $dddd_i = 0;
            ($msg === '1234567890123') ?: PC::debug($msg, $title ?: $dddd_i);
            $dddd_i++;
    }
}
```

If I try to execute: 

```
        try {
            /** @var $request Mage_Api2_Model_Request */
            $request = Mage::getSingleton('api2/request');
            dddd($request, '$request = Mage::getSingleton(api2/request);');"
            .....
       }
```

in the page of "{magento}\app\code\core\Mage\Api2\Model\Server.php", the program will be terminated.

I checked the source-code of php-console and found the termination is caused by this line:
     `if($this->detectCallbacks && count($data) == 2 && is_callable($data)) {`

It's in the function dumpVarData() in Dumper.php, actually terminated by the function "is_callable()".

When the function encounters an array['GET', ''], the program will be terminated in this circumstance. It seems that  it only could happen in some complicated environment. I tested PC:debug(['_GET', '']) at the beginning of the program and it works fine.

**Comment by barbushin** [comment]
So if you open `/src/PhpConsole/Dumper.php` and comment this lines

```
			if($this->detectCallbacks && count($data) == 2 && is_callable($data)) {
				list($class, $method) = $data;
				$data = '(callback ' . (is_object($class) ? get_class($class) : $class) . '::' . $method . ')';
				$sizeLeft -= strlen($data) + 4;
				return;
			}
```

Then everything will works?

**Comment by ukalpa** [comment]
Yeah, I modified the code as follows:

			if($this->detectCallbacks && count($data) == 2)
			{
				if (current($data) == '_GET')
				{
					$data = 'Data "_GET"';
					$sizeLeft -= strlen($data) + 4;
				}
				else
				{
					if($this->detectCallbacks && count($data) == 2 && is_callable($data)) {
						list($class, $method) = $data;
						$data = '(callback ' . (is_object($class) ? get_class($class) : $class) . '::' . $method . ')';
						$sizeLeft -= strlen($data) + 4;
						return;
					}
				}
			}
