### ISSUE TITLE
Connecting to raw IPv6 address causes loop

### ISSUE THREAD

**Issue by xrobau** [barbushin/php-console#96]
A valid IPv6 address looks like this:

http://[2001:4830:121e:fffe:250:56ff:fe9c:9ac1]/admin/config.php

When  trying to connect to that address with PHP Console enabled in chrome, background is crashing with this error:

Unchecked runtime.lastError while running cookies.set: Invalid url: "http://[2001".
    at Object.callback (chrome-extension://nfhmhhlpfleoednkpnnnkolmclajemef/background.js:7:364)

I'm guessing you're trying to split on colon, which isn't correct, obviously.

**Comment by barbushin** [comment]
Fixed in PHP Console 2.0.36. Please check if your extension is updated to last version https://chrome.google.com/webstore/detail/php-console/nfhmhhlpfleoednkpnnnkolmclajemef
