### ISSUE TITLE
A potential conflict with Laravel 5

### ISSUE THREAD

**Issue by ukalpa** [barbushin/php-console#97]
In some unknown circumstances, Activating session would conflict with Laravel.

When I tried to output a object using php-console, the program was terminated by the error message as follows:

PHP Fatal error:  Uncaught exception 'ErrorException' with message 'session_start(): Cannot send session cache limiter - headers already sent (output started at C:\www\laravel5\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php:1255)' in C:\www\php-console\src\PhpConsole\Storage\Session.php:27
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'session_start()...', 'C:\\www\\php-cons...', 27, Array)
#1 C:\www\php-console\src\PhpConsole\Storage\Session.php(30): session_start()
#2 C:\www\php-console\src\PhpConsole\Connector.php(90): PhpConsole\Storage\Session->__construct()
#3 C:\www\php-console\src\PhpConsole\Connector.php(501): PhpConsole\Connector->getPostponeStorage()
#4 C:\www\php-console\src\PhpConsole\Connector.php(453): PhpConsole\Connector->proceedResponsePackage()
#5 [internal function]: PhpConsole\Connector->onShutDown()
#6 {main}
  thrown in C:\www\php-console\src\PhpConsole\Storage\Session.php on line 27

These are relevant codes in Laravel5:

1241   public static function closeOutputBuffers($targetLevel, $flush)
1242       {
1243           $status = ob_get_status(true);
1244           $level = count($status);
1245   
1246           while ($level-- > $targetLevel
1247               && (!empty($status[$level]['del'])
1248                   || (isset($status[$level]['flags'])
1249                       && ($status[$level]['flags'] & PHP_OUTPUT_HANDLER_REMOVABLE)
1250                       && ($status[$level]['flags'] & ($flush ? PHP_OUTPUT_HANDLER_FLUSHABLE :     PHP_OUTPUT_HANDLER_CLEANABLE))
1251                   )
1252               )
1253           ) {
1254               if ($flush) {
1255                   ob_end_flush();
1256               } else {
1257                   ob_end_clean();
1258               }
1259           }
1260       }

These are relevant codes in Php-Console:

23        public function __construct($sessionKey = '__PHP_Console_postponed', $autoStart = true) {
24        
25        		if($autoStart && (defined('PHP_SESSION_ACTIVE') ? session_status() != PHP_SESSION_ACTIVE : !session_id())) {
26        			file_put_contents('c:\www\test11111.txt', headers_sent() ? 'true': 'false' );  // This row is added by me, I check if the header has been sent, the result is true.
27        			session_start();
28        		}
29        		register_shutdown_function('session_write_close'); // force saving session data if session handler is overridden
30        		$this->sessionKey = $sessionKey;
31        	}

**Comment by barbushin** [comment]
Hi.

First of all you can try to use https://github.com/barbushin/php-console-laravel

Otherwise, if you want to integrate PHP Console with Laravel by yourself, just take a look at https://github.com/barbushin/php-console#troubleshooting-with-_session-handler-overridden-in-some-frameworks 

Cheers!

**Comment by ukalpa** [comment]
OK, I will try it, thank you very much.
