### ISSUE TITLE
Debug output limited to 100 - Chrome or Phpconsole?

### ISSUE THREAD

**Issue by digitaloutback** [barbushin/php-console#99]
Debugging an array of > 100 items, Chrome debug limits to 100 and displays i.e. ...: "(displayed 100 of 108)"

Any advice on removing the limit?

**Comment by barbushin** [comment]
See https://github.com/barbushin/php-console/blob/master/examples/features/debug_vars.php#L36

**Comment by digitaloutback** [comment]
Thanks
